### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by peepo** [mennowo/ofxV4L2#2]
could you please provide a HowTo?

and expand on the requirements?

main.h is not present, and there were a number of other warnings when I tried to build..

**Comment by mennowo** [comment]
Hello,

this is quite a while ago I made this. It was made using a prior (007)
version of OF, though I'm not sure if that could cause trouble. Anyhow I
have been using OF a lot lately. Give me a few days and I will look into it.
Do the example project compile fine with your installment of OF? Which
linux distro are u using?
As for requirements, you need to install the package that has the file
"videodev2.h". I'm in win7 right now so I cannot check.
The file "ofMain.h" is actually not part of the project, but part of
openframeworks itself, at least it was in version 007. So if your
codeblocks (if that's what you use) is set up rightly it should work fine.
The example should build fine when you make a new empty project, and then
put the code from the testapp files into the project... Of course you need
to be sure the ofxV4L2 cpp and h files are included fine.
Please let me know the warnings you get.

Maybe it is also worth checking if and how the native OF videograbber class
may have improved. I did get quite better results with the ofxV4L2 class
when I used it last year. I wrote it specifically to use multiple PS3 eye
camera's which use a lot of usb bandwith (like, almost a the whole possible
bandwith per camera). Using the videograbber class, which is based on
gstreamer (as I recall) did not do the trick for me at that time (low
framerate, lots of dropped frames when using 640x480 with two cams). The
ofxV4L2 class is based quite directly on the examples from the V4L2 api. Do
note that the class only supports black-and-white. Though feel free to
implement other grabbing methods! I 'd be happy to hear about that :-) For
the rest see the example code and the info in the header.

Bye, Menno

On Sat, Mar 9, 2013 at 11:12 PM, peepo notifications@github.com wrote:

> could you please provide a HowTo?
> 
> and expand on the requirements?
> 
> main.h is not present, and there were a number of other warnings when I
> tried to build..
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mennowo/ofxV4L2/issues/2
> .

## 

To ensure safety and privacy, this email will selfdestruct in 5 seconds.
Don't panic!

**Comment by mennowo** [comment]
This is a quite old addon, that does not conform to the new requirements for addons (i.e.: provide an example or readme...). An example and readme may or may not be provided at any point in the near or far future. Good luck!

**Comment by Daandelange** [comment]
For the notice, autr has made some changes a few years ago : https://github.com/autr/ofxV4L2
Looks like he updated the example too.
